### ISSUE TITLE
Unhandled exception on forecast update when not HTTP error

### ISSUE THREAD

**Issue by claustres** [weacast/weacast-core#1]
The following exception is thrown when a forecast update raises an error which is not a HTTP error (eg a conversion error):
```
error: Unhandled Rejection at: Promise  Promise {
  <rejected> TypeError: Cannot read property 'code' of undefined
    at /opt/app/api/node_modules/weacast-core/lib/mixins/mixin.refresh.js:212:19 } TypeError: Cannot read property 'code' of undef                           ined
    at /opt/app/api/node_modules/weacast-core/lib/mixins/mixin.refresh.js:212:19
```

**Comment by claustres** [comment]
Linked also to https://github.com/weacast/weacast-gfs/issues/1.
