### ISSUE TITLE
Update process stopped after download failure

### ISSUE THREAD

**Issue by claustres** [weacast/weacast-core#3]
### Steps to reproduce

Observed in production with the GFS plugin after a long time (~3 weeks).

According to the logs we had some connection problems with the remote server causing the update code to go through this path for some elements (e.g. `gust`): https://github.com/weacast/weacast-core/blob/master/src/mixins/mixin.refresh.js#L37 > https://github.com/weacast/weacast-core/blob/master/src/mixins/mixin.refresh.js#L185:
```
Could not download gfs-world/gust forecast at 2018-04-16T00:00:00Z for run 2018-04-07T12:00:00Z Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TCP.onread (net.js:582:26)
Could not update gfs-world/gust forecast at 2018-04-16T00:00:00Z for run 2018-04-07T12:00:00Z
read ECONNRESET
```

This caused the update process to stop like if the top-level promise was not resolved/rejected. Indeed it was the last message in log regarding the element. For one element it seems that the update process stopped after a complete run however.

### Expected behavior

The update process should handle erroneous data gracefully then grab it again on the next interval.

### Actual behavior

The update process is not launched on the next interval.

**Comment by claustres** [comment]
Closing https://github.com/weacast/weacast-core/issues/2 could also help.
